### ISSUE TITLE
Multicollinearity of dummy variables?

### ISSUE THREAD

**Issue by fohy24** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#10]
Should we drop one level from each categorical variables so to avoid multicollinearity? E.g. drop Pclass1 so that Pclass1 + Pclass2 +Pclass3 doesn't always add up to 1? If Pclass2 and Pclass3 are both 0 we know that the observation is of Pclass1

**Comment by alanpow** [comment]
Hey I don't think with R it's like that since we are working with a single variable to begin with and the dummy variable are made to help the model ingest the various labels within that single variable/column. I think that was more of a topic from Veradas class with dropping the extra binary variable or when we did OneHot... but I'm pretty sure that's an sklearn thing and not to do with R.
