### ISSUE TITLE
Investigation of Potential Multicollinearity Between Pclass and Fare in Titanic Dataset

### ISSUE THREAD

**Issue by Sampsonyu** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#12]
In our recent analysis of the Titanic dataset, we focused on the relationship between various factors and survival rates. Given that these Pclass (Passenger Class) and Fare are potentially correlated (higher fares might be associated with higher classes), there's a need to investigate the presence and impact of multicollinearity.

This issue aims to conduct a deeper analysis to determine whether multicollinearity between Pclass and Fare is influencing our model results.  Maybe we can take a look in milestone 2 or 3

**Comment by alanpow** [comment]
I think this is a fair thing to look at but probably will not be able to approach it this time around. I do however this the multicollinearity isn't that big of a problem here because the summary of our Logistic Regression states the two variables are very significant. Also contextually I saw that even amongst First Class Passengers there was a large variability in Fare prices - so I think even between classes there is added information contributed by Fare. I don't think it unbalances the model and or reduces the precision.
