### ISSUE TITLE
<Peer-Review-Issue>: Model Testing and Validation

### ISSUE THREAD

**Issue by Sampsonyu** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#66]
- The model was not tested on a separate test data set, limiting evaluation of its performance.
- Need to choose and report suitable performance metrics (e.g., accuracy, f1 score).

**Comment by alanpow** [comment]
The reasoning behind this which was explained was because we are just interested in estimation and not prediction - we are just looking at relationships in the data. We could maybe give a metric such as R^2 to show how we explain the variability but our report did not intend to make a predication model and evaluate its performance. I can however go into some more depth about our model metrics .

**Comment by Sampsonyu** [comment]
Closing the issue as it has been addressed in the pr
